/** Single source of truth for URLs, promotion links and UTM tagging. */

const REPO_OWNER = 'intellectwithvivek'
const REPO_NAME = 'chatterbox'

export const site = {
  name: 'ChatterBox',
  tagline: 'Ship a chat UI before lunch',
  url: 'https://chatterbox.vivekkumarsingh.in',
  /** owner/name, as GitHub renders it. */
  repoSlug: `${REPO_OWNER}/${REPO_NAME}`,
  repo: REPO_NAME,
  repoUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}`,
  cloneUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}.git`,
  /** Ready to paste into a terminal — offered with a CopyButton site-wide. */
  cloneCommand: `git clone https://github.com/${REPO_OWNER}/${REPO_NAME}.git`,
  /** GitHub's "create a repo from this template" route. */
  templateUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}/generate`,
  issuesUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}/issues`,
  licenseUrl: `https://github.com/${REPO_OWNER}/${REPO_NAME}/blob/main/LICENSE`,
  description:
    'A free, open-source AI chatbot UI template for React and Next.js. Chat thread, typing indicator, code blocks with copy and charts inside chat bubbles — built with VivekUI, zero runtime dependencies.',
} as const

/** VivekUI, the library this template exists to show off. */
export const vivekui = {
  pkg: '@the_viveksingh/vivek-ui',
  install: 'npm i @the_viveksingh/vivek-ui',
  docs: 'https://ui.vivekkumarsingh.in/docs',
  components: 'https://ui.vivekkumarsingh.in/docs/components',
  npm: 'https://www.npmjs.com/package/@the_viveksingh/vivek-ui',
  github: 'https://github.com/intellectwithvivek/vivek_UI',
  author: 'https://vivekkumarsingh.in/',
  authorName: 'Vivek Kumar Singh',
  blurb:
    'Built with \u2764\ufe0f using VivekUI \u2014 91 React components \u00b7 6 SVG charts \u00b7 zero runtime dependencies. One install, one CSS import, no config.',
} as const

/**
 * The OG card generated by `app/opengraph-image.tsx`.
 *
 * A page that declares its own `openGraph` block stops inheriting the
 * file-convention image, so every child route has to name it explicitly.
 * Resolved against `metadataBase`.
 */
export const ogImage = '/opengraph-image'

const UTM_SOURCE = 'vivekui-template'
const UTM_CAMPAIGN = 'aichat'

/** Tag an outbound VivekUI link so the template's traffic is attributable. */
export function utm(url: string, medium: string): string {
  const sep = url.includes('?') ? '&' : '?'
  return `${url}${sep}utm_source=${UTM_SOURCE}&utm_campaign=${UTM_CAMPAIGN}&utm_medium=${medium}`
}

/** Deep link to one component's docs page, e.g. `ChatThread` -> `.../chat-thread`. */
export function componentDocs(name: string, medium = 'builtwith'): string {
  const slug = name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
  return utm(`${vivekui.components}/${slug}`, medium)
}
